public enum SpellZonePrefabId {
    ZoneExplosionFire,
    ZoneFire,
    ZoneExplosionIce,
    ZoneIce,
    ZoneExplosionToxic,
    ZoneToxic,
    ZoneExplosionForce,
    ZoneForce,
    ZoneExplosionAir,
    ZoneAir,
    ZoneExplosionLightning,
    ZoneLightning,
    ZoneExplosionShadow,
    ZoneShadow,
}